CREATE TABLE BOOKS
(
    ID            INT           NOT NULL AUTO_INCREMENT,
    ID_GENRE      INT           NOT NULL,
    PATH_IMG      VARCHAR(255)  NOT NULL,
    TITLE         VARCHAR(255)  NOT NULL,
    YEAR_OF_ISSUE INT           NOT NULL,
    SUMMARY       VARCHAR(1500) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHORS
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRES
(
    ID    INT          NOT NULL AUTO_INCREMENT,
    GENRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOK_AUTHOR
(
    ID        INT NOT NULL AUTO_INCREMENT,
    ID_AUTHOR INT NOT NULL,
    ID_BOOK  INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USERS
(
    ID    INT          NOT NULL AUTO_INCREMENT,
    ADMIN VARCHAR(255) NOT NULL,
    GUEST VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE BOOKS
    ADD CONSTRAINT GENRE_FK
    FOREIGN KEY (ID_GENRE)
    REFERENCES GENRES(ID);

ALTER TABLE BOOK_AUTHOR
    ADD CONSTRAINT AUTHOR_FK
    FOREIGN KEY (ID_AUTHOR)
    REFERENCES AUTHORS(ID);

ALTER TABLE BOOK_AUTHOR
    ADD CONSTRAINT BOOK_FK
    FOREIGN KEY (ID_BOOK)
    REFERENCES BOOKS(ID);


