INSERT INTO GENRES (GENRE)
VALUES ('ROMANS');



INSERT INTO BOOKS (ID_GENRE, TITLE , PATH_IMG , YEAR_OF_ISSUE , SUMMARY)
VALUES (1, 'SASHALOVE', 'TEST' ,2005, 'HE LOVE SHE')

INSERT INTO BOOKS (ID_GENRE, TITLE, PATH_IMG, YEAR_OF_ISSUE, SUMMARY)
VALUES (1, 'Di', 'TEST', 2012, 'HE LOVE SHE');




INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME , PATRONYMIC )
VALUES ('Balet', 'heey', 'hell')